//
//  GreetingData.swift
//  ten-week-goal-app
//
//  Written by Claude Code on 2025-11-20
//
//  PURPOSE: Structured data for personalized HomeView greetings
//  PATTERN: @Generable for guided generation with LanguageModelSession
//
//  USAGE: LLM generates this structure based on recent activity, values, and goals
//  OUTPUT: Drives dynamic HomeView greeting (3 lines + optional focus suggestion)
//

import Foundation
import FoundationModels

/// Personalized greeting data generated by LLM based on user activity
/// Used by HomeView to display contextual, motivational greeting messages
@available(iOS 26.0, macOS 26.0, *)
@Generable(description: "Personalized greeting message for user's home dashboard")
public struct GreetingData: Codable {

    // MARK: - Greeting Lines (HomeView 3-line display)

    @Guide(description: "First line: Time-of-day greeting (e.g., 'Good morning', 'Good afternoon')")
    public var timeGreeting: String

    @Guide(description: "Second line: Motivational phrase or status (e.g., 'Here's what's', 'You're making progress', 'Strong momentum')")
    public var motivationalLine1: String

    @Guide(description: "Third line: Continuation or specific insight (e.g., 'happening', 'on your goals', 'this week')")
    public var motivationalLine2: String

    // MARK: - Context (informational, not displayed directly)

    @Guide(description: "Type of greeting: 'momentum', 'values_driven', 'focus_suggestion', 'welcome_back', or 'balanced'")
    public var greetingType: String

    @Guide(description: "Optional hero image name from asset catalog (e.g., 'Mountains4', 'Sunrise', 'Forest')")
    public var suggestedHeroImage: String?

    @Guide(description: "Optional focus suggestion if user should attend to a specific goal")
    public var focusSuggestion: FocusSuggestion?

    // MARK: - Initializer

    public init(
        timeGreeting: String,
        motivationalLine1: String,
        motivationalLine2: String,
        greetingType: String,
        suggestedHeroImage: String? = nil,
        focusSuggestion: FocusSuggestion? = nil
    ) {
        self.timeGreeting = timeGreeting
        self.motivationalLine1 = motivationalLine1
        self.motivationalLine2 = motivationalLine2
        self.greetingType = greetingType
        self.suggestedHeroImage = suggestedHeroImage
        self.focusSuggestion = focusSuggestion
    }
}

/// Optional suggestion for user to focus on a specific goal
@available(iOS 26.0, macOS 26.0, *)
@Generable(description: "Suggestion to focus on a specific goal that needs attention")
public struct FocusSuggestion: Codable {
    @Guide(description: "Goal ID that needs attention")
    public var goalId: String

    @Guide(description: "Goal title to display")
    public var goalTitle: String

    @Guide(description: "Reason for suggestion (e.g., 'No actions in 7 days', 'Deadline in 3 days')")
    public var reason: String

    @Guide(description: "Days since last action on this goal", .range(0...365))
    public var daysSinceLastAction: Int

    public init(
        goalId: String,
        goalTitle: String,
        reason: String,
        daysSinceLastAction: Int
    ) {
        self.goalId = goalId
        self.goalTitle = goalTitle
        self.reason = reason
        self.daysSinceLastAction = daysSinceLastAction
    }
}
